Yy feature login
redacademy/STCSummer2019 pull request #29
Opened 2019-09-05 20:37 UTC by verasunyy

add sign-in and sign-up screen,
add authentication in the root nav,
add asyncStorage for user token

2019-09-05 23:19 UTC, siddharthparmar7 requested changes
Nice work! Please make the changes. Thank you.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/App.js
> +      {/* <SignUp /> */}
remove this commented code.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/App.js
> +import SignUp from './screens/SignUp';
remove unnecessary imports.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/config/models/Authentication.js
> +    console.log(token)
remove this console log.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/config/models/Authentication.js
> +import AsyncStorage from '@react-native-community/async-storage';
use camelCase for your file names in models dir.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/screens/AuthLoading/AuthLoading.js
> +      <View>
remove View component wrapper. Create a Loader component if needed.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/screens/Profile/Profile.js
> +            // const userToken = await queryToken()
remove commented code.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignIn.js
> +    console.log(navigation)
remove console log.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignIn.js
> +                console.log("submit", values.email)
remove console logs.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignIn.js
> +                      console.log("jsbdfjhdakjfhd")
remove console log.

2019-09-05 23:19 UTC, siddharthparmar7 commented on client/js/screens/SignIn/SignInContainer.js
> +export default SignInContainer;
remove all the commented code.

2019-09-06 02:24 UTC, verasunyy commented on client/js/App.js
> +      {/* <SignUp /> */}
done

2019-09-06 16:38 UTC, siddharthparmar7 approved these changes

2019-09-06 16:38 UTC, merged