Yy feature createreadme
redacademy/STCSummer2019 pull request #88
Opened 2019-09-16 18:17 UTC by yenyin262

fixed markdown

2019-09-16 18:36 UTC, siddharthparmar7 requested changes
Nice work! Please make the changes. Thank you.

2019-09-16 18:36 UTC, siddharthparmar7 commented on README.md
> +![Simulator Screen Shot - iPhone X - 2019-09-13 at 13 43 46](https://user-images.githubusercontent.com/43800526/64897309-d1a04e00-d637-11e9-8e3f-e0faa4190614.png)
Please provide a gif file that shows different screens from your app.

2019-09-16 18:36 UTC, siddharthparmar7 commented on README.md
> +```pod install```
Please provide detailed instructions on how to run your app.
cd into client dir
yarn install
cd into ios
pod install
go back to client dir
run your app.

2019-09-16 18:36 UTC, siddharthparmar7 commented on README.md
> +```GraphQL```
Do not need to add GraphQL as a separate technology. GraphCool is using GraphQL.

2019-09-16 18:36 UTC, siddharthparmar7 commented on README.md
> +```	React Native```
why is that a huge space before the word react native?

2019-09-16 18:36 UTC, siddharthparmar7 commented on README.md
> +```Apollo-Client```
just write Apollo.

2019-09-16 18:36 UTC, siddharthparmar7 commented on README.md
> +```React-Native Tab-Views```
No need to include the packages you installed.

2019-09-16 20:15 UTC, siddharthparmar7 requested changes

2019-09-16 20:15 UTC, siddharthparmar7 commented on README.md
> +```cd into ios```
Write the actual commands, not pseudo-code. It was just to show you the steps.

2019-09-16 20:15 UTC, siddharthparmar7 commented on README.md
> +```React-Native Maps```
it's a library. Please give info if you are using Apple maps or Google maps

2019-09-16 20:15 UTC, siddharthparmar7 commented on README.md
> +# Technologies:
It should not be an H1 title. Use the same level of heading as other sections in your README.

2019-09-16 20:15 UTC, siddharthparmar7 commented on README.md
> +# Instructions to run the project
This should be an H1 heading. Please change it.

2019-09-16 23:57 UTC, piahmed approved these changes
Looks good :+1:

2019-09-17 00:05 UTC, imran-pi commented
Hey @siddharthparmar7 I'm merging this as @yenyin262 is a bit stressed and was looking to merge. If you think this requires additional changes, please let her know. Thanks!

2019-09-17 00:05 UTC, merged