Sd feature clean up
redacademy/STCSummer2019 pull request #90
Opened 2019-09-16 19:18 UTC by sydneydou

### Change clothes to clothing
### Clean up code

2019-09-16 20:04 UTC, siddharthparmar7 requested changes

2019-09-16 20:04 UTC, siddharthparmar7 commented on client/yarn.lock
> +>>>>>>> develop
Please resolve merge conflicts.

2019-09-17 20:13 UTC, iyuvraajsingh submitted a review, later dismissed

2019-09-17 21:06 UTC, iyuvraajsingh approved these changes

2019-09-17 21:06 UTC, merged